### ISSUE TITLE
A little question about DAG+SAT

### ISSUE THREAD

**Issue by AwdHanPeng** [LUOyk1999/DAGformer#1]
Hi, thanks for your work.
I have a littel question:  whether the RWPE in original SAT is still added in your DAG+SAT model? or just the new PE your proposed is included?
Thanks.

**Comment by LUOyk1999** [comment]
We did not add RWPE. But we also did experiments with RWPE, which has the same performance as DAGPE. However, in the original SAT they did not add RWPE.
![image](https://user-images.githubusercontent.com/57895481/200112190-a4f15246-7f95-4c45-aac6-92cc09d83904.png)

**Comment by AwdHanPeng** [comment]
Thanks so much!
