### ISSUE TITLE
Question about cora and citeseer dataset

### ISSUE THREAD

**Issue by vickychen928** [LUOyk1999/DAGformer#3]
I'd like to inquire about why the processing methods for the `cora` and `citeseer` datasets differ in `Node_classification_citation/dataset.py,` as shown in the image below. When processing the `cora` dataset, a graph `new_G` is first constructed, then directly converted to an undirected graph `new_G_undirected` without removing cycles from `new_G` beforehand. However, when processing the `citeseer` dataset, cycles are first removed from `new_G` before it is converted into an undirected graph. I'm curious to understand the reason behind this reversal in order. Thank you.
![image](https://github.com/LUOyk1999/DAGformer/assets/84194000/e8ccedcd-fb20-4e30-9bf9-c5472e7227ca)

**Comment by LUOyk1999** [comment]
Thank you for pointing that out. Our method uses edge_index_dag, which is constructed by removing directed cycles. The new_G_undirected is used to generate the edge_index for the undirected graph used in the baseline method. The correct procedure here is to directly obtain the undirected graph without removing directed cycles. The code will be updated accordingly. We have conducted experiments in both scenarios, and the results are similar.

**Comment by vickychen928** [comment]
Thank you so much!
